# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_todoinfo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
